version: "3.8"
services:
  backend:
    container_name: payunionpro_backend
    build: ./backend
    image: payunionpro_backend:1.0.0
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    container_name: payunionpro_frontend
    build: ./frontend
    image: payunionpro_frontend:1.0.0
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
